/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
export type ProductsQuery = {
    allProducts: {
        count: number;
        nodes: ({
            id: string;
            name: string;
            price: number;
        } & ProductPrice)[];
    };
};
export type ProductsQueryVariables = {
    enableStream: boolean;
};
export type ProductPrice = {
    specialPrice: number | null;
};
